### ISSUE TITLE
Just released my own fantasy console: DreamBox

### ISSUE THREAD

**Issue by GlaireDaggers** [paladin-t/fantasy#85]
Would like to suggest my own fantasy console for this list, which I just released the very first alpha build of: DreamBox.
It's NYOP on itch.io, heavily inspired by the 2nd-gen consoles of the 2000s (completely fixed-function 3D pipeline, no multi-texturing, no hardware T&L, displays at 640x480, PCM sample playback support, MIDI playback support), and runs WASM games! :)

https://dreambox3d.dev/
https://crit-chance-studios.itch.io/dreambox

**Comment by paladin-t** [comment]
Hi, your console looks great and it has a potential, it is well made and has good documents. However I could not add the current version to the list, because it is lack of "easy to start with", in particular, it requires too many external installations before get started. One important attraction of fantasy consoles is that as a user, I can get everything ready to use within one or two clicks.

**Comment by GlaireDaggers** [comment]
Thanks for the feedback!
As of now, DreamBox has a brand new Rust SDK and everything needed to create a new project is published on Cargo, so the setup process has been *significantly* simplified and can be performed in just a few commands, relying on only a single external installation (the Rust toolchain):

```
cargo install dbsdk-cli
dbsdk-cli new hello-dreambox
cargo add dbsdk-rs
dbsdk-cli build .
```

Was this more in line with what you were thinking?

**Comment by paladin-t** [comment]
Added, thanks for the info! Feel free to update it with future changes.
